<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- NuGet Package Properties -->
    <PackageId>BetterDev.ShadcnBlazor</PackageId>
    <Version>1.0.1</Version>
    <Authors>Better-Dev-Team</Authors>
    <Company>Better-Dev-Team</Company>
    <Description>Beautifully designed, accessible, copy-paste and package-ready Razor components for Blazor inspired by shadcn/ui.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Better-Dev-Team/shadcn-blazor</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Better-Dev-Team/shadcn-blazor</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>blazor;shadcn;shadcn-ui;tailwind;components;ui;razor;dotnet;csharp</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
  </ItemGroup>

</Project>
